name: 'dbt_med'
version: '1.0.0'
profile: 'dbt_med'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  analysis:
    remove_duplicates:
      description: 'Removes duplicate rows based on message_id'
      materialized: view
      schema: 'analysis'
      columns:
        - name: id
          description: 'Unique identifier for the message'
        - name: channel
          description: 'The channel the message was posted in'
        - name: message_id
          description: 'Unique identifier for the message'
        - name: content
          description: 'The content of the message'
        - name: message_link
          description: 'The URL link to the message'
        - name: timestamp
          description: 'The timestamp when the message was posted'
        - name: views
          description: 'The number of views the message received'

    handle_missing_values:
      description: 'Handles missing values in the dataset'
      materialized: view
      schema: 'analysis'
      columns:
        - name: id
          description: 'Unique identifier for the message'
        - name: channel
          description: 'The channel the message was posted in'
        - name: message_id
          description: 'Unique identifier for the message'
        - name: content
          description: 'The content of the message'
        - name: message_link
          description: 'The URL link to the message'
        - name: timestamp
          description: 'The timestamp when the message was posted'
        - name: views
          description: 'The number of views the message received'

    standardize_formats:
      description: 'Standardizes formats in the dataset'
      materialized: view
      schema: 'analysis'
      columns:
        - name: id
          description: 'Unique identifier for the message'
        - name: channel
          description: 'The channel the message was posted in'
        - name: message_id
          description: 'Unique identifier for the message'
        - name: content
          description: 'The content of the message'
        - name: message_link
          description: 'The URL link to the message'
        - name: timestamp
          description: 'The timestamp when the message was posted'
        - name: views
          description: 'The number of views the message received'

    fact_telegram:
      description: 'Final transformed table with message length'
      schema: 'analysis'
      columns:
        - name: id
          description: 'Unique identifier for the message'
        - name: channel
          description: 'The channel the message was posted in'
        - name: message_id
          description: 'Unique identifier for the message'
        - name: content
          description: 'The content of the message'
        - name: timestamp
          description: 'The timestamp when the message was posted'
        - name: views
          description: 'The number of views the message received'
        - name: message_link
          description: 'The URL link to the message'
        - name: message_length
          description: 'The length of the message content'
      materialized: table
      partition_by:
        field: timestamp
        data_type: timestamp
      unique_key: id
