dbt_med:
  target: dev
  outputs:
    dev:
      type: postgres
      host: your_host
      user: your_username
      password: your_password
      port: 5432
      dbname: your_dbname
      schema: analysis
      threads: 4
